name: Deploy PuppyCare SSH
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3                 # ‚Üê OUTRA ACTION!
        with:
          host: 1113770                
          username: main
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/main/puppycare/back-end
            git pull origin main
            docker-compose down 
            docker-compose up -d
