name: Deploy PuppyCare Hostinger SSH
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 147.79.82.92                
          username: main
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            git pull private main
            cd back-end
            docker-compose down 
            docker-compose up -d
