name: Deploy - Hostinger
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy - Hostinger
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 147.79.82.92                
          username: main
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            pm2 stop all
            git pull private main
            cd back-end
            npm install
            npm run build
            cd ..
            cd front-end
            npm install
            npm run build
            sudo npx playwright install-deps
            npx playwright install
            npx playwright test
            pm2 start all
            
