name: Deploy PuppyCare on Push Main
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy Back-end Hostinger VPS
        uses: hostinger/deploy-on-vps@v2
        with:
          host: "srv1113770.hstgr.cloud"
          username: main
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/main
            git pull isaac main
            docker-compose down
            docker-compose up

